sudo: true
# dist: trusty
language: rust
cache:
  cargo: true
  directories:
    - "$VITASDK/src"
    - "$VITASDK/bin"

addons:
  apt:
    packages:
    - libssl-dev

rust:
  - nightly

env:
  global:
    - VITASDK="$HOME/.local/share/vitasdk"
    - PATH="$VITASDK/bin:$PATH"
    - CARGO_MAKE_URL="https://bintray.com/sagiegurari/cargo-make/download_file?file_path=cargo-make_v"

before_install: # bootstrap cargo-make from latest available bintray release
  - cargo install --debug cargo-make -f

install:
  - cargo make ci-install-vdpm

script:
  - cargo make test-native      # Check the library works
  - cargo make build           # Check is compiles to armv7-vita-eabihf

# deploy:
#   provider: script
#   script: cargo make publish-flow
#   on:
#     tags: true
#     repo: vita-rust/vitalloc
#     rust: stable

notifications:
  email:
  - althonosdev@gmail.com
