sudo: false
# dist: trusty
language: rust
cache:
  cargo: true
  directories:
    - "$VDPM_GIT_DIR"
    - "$SCCACHE_DIR"

addons:
  apt:
    packages:
    - libc6-i386
    - lib32stdc++6
    - lib32gcc1
    - patch

rust:
  - nightly

env:
  global:
    # sccache
    - CARGO_HOME="$HOME/.cargo"
    - RUSTC_WRAPPER="sccache"
    - SCCACHE_DIR="$HOME/.cache/sccache"
    # vitasdk
    - VDPM_GIT_DIR="$HOME/.cache/vdpm"
    - VITASDK="$HOME/.local/share/vitasdk"
    - PATH="$VITASDK/bin:$PATH"

install:
  - ci/travis/setup.sh

script:
  - cargo make test-native     # Check the library works
  - cargo make build           # Check is compiles to armv7-vita-eabihf

# deploy:
#   provider: script
#   script: cargo make publish-flow
#   on:
#     tags: true
#     repo: vita-rust/vitalloc
#     rust: stable

notifications:
  email:
  - althonosdev@gmail.com
