extend = "common.toml"

[env]
# Project information
TITLE = "Rust Hello World"
TITLEID = "RUST00001"

[config]
load_script = [
    """
    if [ ! -f common.toml ]; then
        curl -SsL https://github.com/vita-rust/common/raw/master/common.toml > common.toml
    fi
    """
]

[tasks.build-native]
command = "cargo"
args = ["build"]

[tasks.test-native]
command = "cargo"
args = ["test"]
