extend = "common.toml"

[env]
COMMON_TOML = "https://github.com/vita-rust/common/raw/master/common.toml"

[config]
load_script = ["if [ ! -f common.toml ]; then curl -SsL ${COMMON_TOML} > common.toml; fi"]

[tasks.default]
alias = "build"


### CI #########################################################################

[tasks.build-native]
command = "cargo"
args = ["build"]

[tasks.test-native]
command = "cargo"
args = ["test"]

[tasks.ci-install-vdpm]
condition = { env = { "TRAVIS" = "true" } }
script = [
  'mkdir -p "$VITASDK/src/vdpm"',
  'cd "$VITASDK/src/vdpm"',
  '[ -d ".git" ] && git pull || git clone https://github.com/vitasdk/vdpm',
  './bootstrap-vitasdk.sh',
  './install-all.sh',
]
